services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ayacoo\ArdSounds\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Event/*'
      - '../Classes/Helper/*'

  Ayacoo\ArdSounds\Helper\ArdSoundsHelper:
    arguments:
      $extension: 'ardsounds'

  Ayacoo\ArdSounds\Command\UpdateMetadataCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'ardsounds:updateMetadata'
        description: 'Updates the ARD Sounds metadata'
        schedulable: true
